#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server

file_path="$1"
ip="$2"
username="$3"
ssh_key="$4"

if [ $# -lt 4 ];
then
	echo "Usage: 0-transfer_file file_path IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username@$ip":~/
fi
