#!/usr/bin/env bash
# install ngix listening at port 80

echo -e "Updating package lists and installing Nginx...\n"

sudo apt-get update -y -qq && sudo apt-get install nginx -y

echo -e "\nStarting Nginx service..."

sudo service nginx start

echo -e "\nAllowing Nginx HTTP traffic through firewall..."
sudo ufw allow 'Nginx HTTP'

echo -e "\nSetting permissions for web directory..."
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo -e "\nBacking up default Nginx index file and creating new index file..."
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp


echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

echo -e "\nConfiguring Nginx to redirect /redirect_me..."
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart

echo -e "\nCompleted" 
