#!/usr/bin/env bash
# install ngix listening at port 80

echo -e "Updating package lists and installing Nginx...\n"

sudo apt-get update -y -qq && sudo apt-get install nginx -y

echo -e "\nStarting Nginx service..."

sudo service nginx start

echo -e "\nAllowing Nginx HTTP traffic through firewall..."
sudo ufw allow 'Nginx HTTP'

echo -e "\nSetting permissions for web directory..."
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo -e "\nBacking up default Nginx index file and creating new index file..."
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp


echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
echo -e "Ceci n'est pas une page" > /var/www/html/404.html

echo -e "\nConfiguring Nginx custom 404 page..."
echo "server {
    listen 80;
    server_name _;
    root /var/www/html;
    error_page 404 /404.html;
    location = /404.html {
    internal;
}

}" | sudo tee -a /etc/nginx/sites-available/default > /dev/null
sudo service nginx restart

echo -e "\nCompleted" 
