#!/usr/bin/env bash
#configures a brand new Ubuntu machine to
#the requirements asked in this task

#update packages
echo -e "updating packages... \n"
function install() {
	command -v "$1" &> /dev/null

	#shellcheck disable=SC2181
	if ! command -v "$1" &> /dev/null; then
		echo -e "	installing: $1$\n"
		sudo apt-get update -y -qq 
		sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "	${1} is already installed.\n"
	fi
}
#set up and install nginx
install nginx

#allows nginx on firewall
sudo ufw allow 'Nginx HTTP'

#give user ownership to website files for easy editing

if [ -d "/var/www" ]; then
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -r 755 /var/www
else
	sudo mkdir -p /var/www
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -R 755 /var/www
fi
for dir in /var/www/{html,error}; do
	if ! [ -d "$dir" ]; then
		mkdir -p "$dir"
	fi
done

#print out 'Hello World'
echo "Hello World!" > /var/www/html/index.html

#error page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

#backup default server configuration
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup

server_config=\
"server {
		listen 80 default_server;
		listen [::]:80 default_server;
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html
		server_name _;
		add_header X-Served-By \$hostname;
		location / {
			try_files \$uri \$uri/ =404;
		}
		if (\$request_filename ~ redirect_me){
			rewrite ^ https://twitter.com/highrate00 permanent;
		}
		error_page 404 /error_404.html;
		location = /error_404.html {
			internal;
		}
}"

echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
