#!/usr/bin/env bash
#Bash script that displays listening ports

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q send-Q Local Address		foreign Adress		State		PID/Program game"

netstat -tlnp | grep 'tcp' | awk '{print $1,$4,$5,$6,$7}' | while read line; do
	pid=$(echo $line | awk '{print $7}' | cut -d'/' -f1)
	pname=$(ps -p $pid -o comm=)
	echo $line $pid/$pname
done

netstat -ulnp | grep 'udp' | awk '{print $1,$4,$5,$6,$7}' | while read line; do
	pid=$(echo $line | awk '{print $7}' | cut -d'/' -f1)
	pname=$(ps -p $pid -o comm=)
	echo $line $pid/$pname
done
