#!/usr/bin/env bash
#it Creates the file /var/run/myscript.pid containing its PID
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal

clean_up_and_exit()
{
	rm /var/run/myscript.pid
	exit $?
}
trap 'echo "I hate the kill command";clean_up_and_exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'clean_up_and_exit' SIGQUIT
echo $$ > "/var/run/myscript.pid"
