#!/usr/bin/env bash
#script that stops 4-to_infinity_and_beyond process.

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -z "pid" ]
then
	echo "4-to_infinity_and_beyond process is not running."
else
	kill "$pid"
fi
