#!/usr/bin/env bash
#Dispays infinity and beyond indefinitely
#Displays a sleep 2 in between each iteration
#Displays I am invincible!!! when receiving a SIGTERM signal

trap "echo 'I am invincible!!!'" SIGTERM
while "true"
do
	echo "To infinity and beyond"
	slep 2
done
