#!/usr/bin/env bash
#it displays the content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

list=$(ls)
for i in $list; do
	echo "$i" | cut -d "-" -f2
done
