#!/usr/bin/env bash
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
pkill -l apache2
chmod +wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf
su nginx -c 'nginx'
