#!/usr/bin/env bash
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/ -R
chmod ugo+wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf | sudo -u nginx service nginx restar
