#!/usr/bin/env bash
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
sudo pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
